### ISSUE TITLE
Support $count on expanded resources

### ISSUE THREAD

**Issue by thgreasi** [balena-io/pinejs#188]
It would be great if we could do something like
```
pine.get({ 
    resource: 'parentResource', 
    options: { 
        $select: ['id', 'name'], 
        $expand: { 
            'childResource/$count': {}, 
        }, 
    }, 
})
```
Obviously, no strong opinion on how the code should look, just trying to make clear what I'm trying to achieve. Adding it to the `$select` list might be preferable.

See: https://www.flowdock.com/app/rulemotion/resin-tech/threads/-vbVIG5okIcLis2FPysRIvlDQrB

**Comment by Page-** [comment]
It's already support via odata so it just needs https://github.com/resin-io/pinejs-client-js/pull/63 to be merged and picked up here for that to be available

**Comment by dfunckt** [comment]
This is done.
